### ISSUE TITLE
Copy the latest colors from the old UI Kit

### ISSUE THREAD

**Issue by vic-topcoder** [topcoder-platform/topcoder-react-ui-kit#1]
@birdofpreyru - I've fixed the wrong colors in our `_variables.scss` https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss

These are the correct colors and semantically separating color names from variable names. They work as a drop-in replacement without any need to refactor the code right away. I saw we missed the yellow gamma entirely, while there was a gold one that I didn't define.

Please make sure we're using the correct colors from the file I shared.

**Comment by birdofpreyru** [comment]
Ok, done, the demo page is temporarily here: https://community-app.topcoder-dev.com/examples/color-mixins

**Comment by vic-topcoder** [comment]
Looks great! I'll include this with all design specs from now on! 👍
